config/routes.rb
Rails.application.routes.draw do
  get 'sales/index'

  get 'sales/new'

  get 'sales/create'

  get 'sales/edit'

  get 'sales/update'

  post 'sales/delete'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/users/new', to: 'users#new'
  #post '/users', to: 'users#create'
  resources :users #, only: [:new, :create] "Only se encarga de definir las partes que necesiteos del CRUD"
  resources :sales
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :product_name, :price, :quantity, :sale_date, presence: true
  
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name, :password, presence: true
  validates_presence_of :password, :on => :create

  has_many :sales
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :user_signed_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def authenticate_user!
    redirect_to root_path, alert: 'Debes de iniciar sesion' unless user_signed_in?
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_sale, only: %i[show edit update destroy]
  def index
    @pagy, @sales = pagy(Sale.all, items: 5)
  end

  def show;
    # @sale = Sale.find params[:id]
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = current_user.sales.new sale_params
    if @sale.save
      return redirect_to sales_path, notice: 'registred sale!'
    end

    render :new
  end

  def edit;
    # @sale = Sale.find params[:id]
  end

  def update
    # @sale = Sale.find params[:id]

    if @sale.update sale_params
      return redirect_to sales_path, notice: 'edited sale'
    end
    render :edit
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    return redirect_to sales_path, alert: 'removed sale!'
  end

  private

  def sale_params
    params.require(:sale).permit(:product_name, :price, :quantity, :sale_date)
  end

  def set_sale
    @sale = Sale.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged In!'
    else
      flash.now[:alert] = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user_params
      return redirect_to root_url, notice: 'Logged In!'
    end

    render :new
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def flash_class(key)
    case key
    when 'notice' then 'is-success'
    when 'alert' then 'is-danger'
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comun/_flash_mensages.html.erb
<% flash.each do |key, value| %>
  <div class="notification <%= flash_class(key) %>">
    <%= value%>
  </div>
<% end %>

app/views/comun/_form_sales.html.erb
  <%= form_for @sale, builder: BulmaFormBuilder do |f| %>
    <%= f.form_error %>
      <div class="field">
      <%= f.label :product_name, class: 'label' %>
        <div class="control">
        <%= f.text_field :product_name, class: 'input' %>
        </div>
        <%= f.field_error :product_name %>
      </div>

      <div class="field">
      <%= f.label :price, class: 'label' %>
        <div class="control">
        <%= f.text_field :price, class: 'input' %>
        </div>
        <%= f.field_error :price %>
      </div>

      <div class="field">
      <%= f.label :quantity, class: 'label' %>
        <div class="control">
        <%= f.text_field :quantity, class: 'input' %>
        </div>
        <%= f.field_error :quantity %>
      </div>

      <div class="field">
      <%= f.label :sale_date, class: 'label' %>
        <div class="control">
        <%= f.date_field :sale_date, class: 'input' %>
        </div>
        <%= f.field_error :sale_date %>
      </div>
    <%= submit_tag nil, class: 'button is-success' %>
  <% end %>

app/views/comun/_navbar.html.erb
<nav class="navbar is-success" role="navigation" aria-label="main navigation">

<div id="navbarBasicExample" class="navbar-menu">
<div class="navbar-start">
  <%= link_to t('global.menu.Home'), root_path, class: 'navbar-item' %>
  <% if user_signed_in? %>
  <%= link_to t('global.menu.Products'), sales_path, class: 'navbar-item' %>
  <% end %>
</div>

<div class="navbar-end">
  <div class="navbar-item">
    <div class="buttons">
      <% if user_signed_in? %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= current_user.name %>
        </a>
        <div class="navbar-dropdown">
          <%= link_to t('global.menu.Log out'), logout_path, class: 'navbar-item' %>
        </div>
      </div>
      <% else %>
      <%= link_to t('global.menu.Sign up'), signup_path, class: 'button is-primary' %>
      <%= link_to t('global.menu.Log in'), login_path, class: 'button is-ligth' %>
      <% end %>
    </div>
  </div>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- <html>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html> -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Prototipo 1</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>
    <%= render "comun/navbar" %>
  <section class="section">
    <div class="container">
      <%= render "comun/flash_mensages" %>
      <%= yield %>
      <h1 class="title">
      </h1>
      <p class="subtitle">
        <!-- My first website with <strong>Bulma</strong>! -->
      </p>
    </div>
  </section>
  </body>
</html>

app/views/sales/create.html.erb
<h1>Sales#create</h1>
<p>Find me in app/views/sales/create.html.erb</p>

app/views/sales/edit.html.erb
<h1 class="title">Editar registro con id: <%= @sale.id %></h1>
<%= render 'comun/form_sales' %>

app/views/sales/index.html.erb
<p class="title">Ventas de <%= current_user.name %></p>
<div class="columns is-desktop is-multiline">
  <div class="card content">
    <table class="table is-bordered">
      <thead>
        <tr>
          <th>Id</th>
          <th><%= t('views.sales.index.Product_Name') %></th>
          <th><%= t('views.sales.index.Price') %></th>
          <th><%= t('views.sales.index.Sold_Quantity') %></th>
          <th><%= t('views.sales.index.Sale_Date') %></th>
          <th><%= t('views.sales.index.Total_Sale') %></th>
        </tr>
      </thead>
        <tbody>
          <% @sales.each do |sale| %>
          <tr>
            <th><%= link_to( sale.id, sale_path(sale)) %></th>
            <td><%= sale.product_name %></td>
            <td><%= sale.price %></td>
            <td><%= sale.quantity %></td>
            <td><%= sale.sale_date %></td>
            <td><%= sale.price * sale.quantity %></td>
            <td><%= link_to t("views.sales.index.Edit"), controller: "sales", action: "edit", id: sale.id %><td>
            <td><%= link_to t("views.sales.index.Delete"), sale_path(sale), method: 'delete', data: { confirm: 'Are you sure?' }  %><td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
<%= link_to t('views.sales.index.Add_Product'), new_sale_path, class: 'button is-success' %>
<%== pagy_bulma_nav(@pagy) %>

app/views/sales/new.html.erb
<h1 class="title">Registrar Venta</h1>
<%= render 'comun/form_sales' %>

app/views/sales/show.html.erb
<h1 class="title"><%= @sale.product_name %></h1>

app/views/sales/update.html.erb
<h1>Sales#update</h1>
<p>Find me in app/views/sales/update.html.erb</p>

app/views/users/VBeta.new.html.erb
%= form_for @user do |f| %>

<%- if @user.errors.any? %>
<div class="notification is-danger">
    <%= t'user.errors' %>
</div>
<% end %>
<div class="field">
  <%= f.label :name, class: 'label' %>
<div class="control">
  <%= f.text_field :name, class: 'input' %>
</div>
  <%- if @user.errors[:name].any? %>
    <div class="help is-danger">
        <%= @user.errors[:name].first %>
    </div>
  <% end %>
</div>
<div class="field">
  <%= f.label :email, class: 'label' %>
<div class="control">
  <%= f.text_field :email, class: 'input' %>
</div>
<%- if @user.errors[:email].any? %>
  <div class="help is-danger">
      <%= @user.errors[:email].first %>
  </div>
<% end %>
</div>
<div class="field">
  <%= f.label :password, class: 'label' %>
<div class="control">
  <%= f.password_field :password, class: 'input' %>
</div>
<%- if @user.errors[:password].any? %>
  <div class="help is-danger">
      <%= @user.errors[:password].first %>
  </div>
<% end %>
</div>
<div class="field">
  <%= f.label :password_confirmation, class: 'label' %>
<div class="control">
  <%= f.password_field :password_confirmation, class: 'input' %>
</div>
<%- if @user.errors[:password_confirmation].any? %>
  <div class="help is-danger">
      <%= @user.errors[:password_confirmation].first %>
  </div>
<% end %>
</div>
  <%= f.submit class: 'button is-success' %>
  <% end %>

app/views/users/new.html.erb
<%= form_for @user, builder: BulmaFormBuilder do |f| %>
  <%= f.form_error %>
  <div class="field">
    <%= f.label :name, class: 'label' %>
    <div class="control">
    <%= f.text_field :name, class: 'input' %>
    </div>
    <%= f.field_error :name %>
  </div>
  <div class="field">
    <%= f.label :email, class: 'label' %>
    <div class="control">
    <%= f.text_field :email, class: 'input' %>
    </div>
    <%= f.field_error :email %>
  </div>
  <div class="field">
    <%= f.label :password, class: 'label' %>
    <div class="control">
    <%= f.password_field :password, class: 'input' %>
    </div>
    <%= f.field_error :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, class: 'label' %>
    <div class="control">
    <%= f.password_field :password_confirmation, class: 'input' %>
    </div>
  <%= f.field_error :password_confirmation %>
  </div>
  <%= f.submit class: 'button is-success' %>
  <% end %>

app/views/welcome/index.html.erb
<p>Prototipo.........</p>